export {
  Table,
  TableContainer,
  TableHeader,
  TableBody,
  TableFooter,
  TableRow,
  TableHead,
  TableCell,
  TableCaption,
  tableVariants,
  tableHeaderVariants,
  tableBodyVariants,
  tableFooterVariants,
  tableRowVariants,
  tableHeadVariants,
  tableCellVariants,
  tableCaptionVariants,
} from './Table.js';

export type {
  TableProps,
  TableContainerProps,
  TableVariant,
  TableHeaderProps,
  TableBodyProps,
  TableFooterProps,
  TableRowProps,
  TableHeadProps,
  TableHeadAlign,
  TableHeadPinned,
  TableCellProps,
  TableCellAlign,
  TableCellPinned,
  TableCaptionProps,
} from './Table.js';
